-- Run in pgweb if POST /api/orders returns 500 (missing columns on orders table).
-- Safe to run multiple times.

ALTER TABLE orders ADD COLUMN IF NOT EXISTS city VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS phone_e164 VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS num_items INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS bundle_subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS upsell_taken BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS upsell_slug VARCHAR(64);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS upsell_price NUMERIC(10, 2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total NUMERIC(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'SAR';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS event_id VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fbp VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fbc VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ttp VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sc_click_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS client_ip VARCHAR(64);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_agent VARCHAR(512);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS landing_url VARCHAR(1024);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS utm JSONB;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sheet_synced BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS capi_result JSONB;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes VARCHAR(1024);

CREATE UNIQUE INDEX IF NOT EXISTS ix_orders_order_number ON orders (order_number);
CREATE INDEX IF NOT EXISTS ix_orders_phone ON orders (phone);
CREATE INDEX IF NOT EXISTS ix_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS ix_orders_event_id ON orders (event_id);

CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    qty INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    is_upsell BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_order_items_order_id ON order_items (order_id);
